### ISSUE TITLE
The original images padded with patches

### ISSUE THREAD

**Issue by JeffereyWu** [AbhishekRS4/HTSM_Oil_Spill_Segmentation#1]
Hello sir. In the data preprocessing step, the original images, in 1250 × 650 dimensions, were padded with patches on all 4 sides of the image to produce resulting images of 1280 × 672. The patch padding was done in such a way as to select a patch of pixels with the sea surface. May I ask what is the benefit of padding the original images with patches?

**Comment by AbhishekRS4** [comment]
The main reason for padding the images is for proper spatial dimension reduction by a factor of multiple of 2. The other reason is to learn better generalization of non-oil pixels.
