### ISSUE TITLE
Dataset Access

### ISSUE THREAD

**Issue by nobleaustine** [AbhishekRS4/HTSM_Oil_Spill_Segmentation#5]
Could you please share the dataset with me I am unable to get the access to the dataset

**Comment by AbhishekRS4** [comment]
Hi, I cannot share the dataset. You can request the dataset access in the following webpage - [Oil Spill Detection dataset](https://m4d.iti.gr/oil-spill-detection-dataset/)

There is a template that your supervisor needs to fill i.e. if you are a research student at a university.
